name= input("Enter name:")
print(name)
Fathers_name=input("Enter Father's name:")
print(Fathers_name )
Mothers_name=input("Enter mother's name:")
print(Mothers_name)
Date_of_Birth=input("Enter date_of_Birth")
print(Date_of_Birth)
age=int(input("Enter age:"))
print(age)
Nationality=input("Enter your nationality:")
print(Nationality)
University=input("Enter your University:")
print(University)